actor:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: ${watch_metric.actor.watch_metric_mode}
  factor: 0.1
  patience: 11111 #before 111
  threshold: 1e-8
  threshold_mode: rel
  cooldown: 0
  min_lr: 0
  eps: 1e-08
  verbose: True

critic:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: ${watch_metric.critic.watch_metric_mode}
  factor: 0.1
  patience: 11111 #before 111
  threshold: 1e-8
  threshold_mode: rel
  cooldown: 0
  min_lr: 0
  eps: 1e-08
  verbose: True